"""
Django settings for attendance_proj project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Look for .env file in the BASE_DIR (QR_Backend directory)
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-sq5@yvc*#8*e_gva93=^d=#^ket&#i^#ymz)7#_orb*i0n!ork')
if not SECRET_KEY or SECRET_KEY.startswith('django-insecure'):
    import warnings
    warnings.warn('SECRET_KEY is not set or using insecure default. Set SECRET_KEY in .env file for production!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Get allowed hosts from environment variable or use default
ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,urqrplate.pythonanywhere.com')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',')]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'attendance',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

ROOT_URLCONF = 'QR_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'QR_Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'  # URL for serving static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']  # This tells Django where to look for static files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# CSRF Trusted Origins - get from environment or use defaults
CSRF_TRUSTED_ORIGINS_STR = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://urqrplate.pythonanywhere.com,https://9865-196-12-151-106.ngrok-free.app')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(',')]

BASE_URL = os.getenv('BASE_URL', 'urqrplate.pythonanywhere.com')
SITE_URL = os.getenv('SITE_URL', 'https://urqrplate.pythonanywhere.com')


# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Use your email provider's SMTP host
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # Gmail address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Gmail App Password (not regular password)
# Default email address for sending emails (should match EMAIL_HOST_USER)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@localhost'
SERVER_EMAIL = EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@localhost'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'

# SESSION_COOKIE_AGE = 600  # Session expires in 10 minutes 
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default session backend

# Session settings - made less restrictive for debugging
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Disabled for easier debugging
SESSION_COOKIE_SAMESITE = 'Lax'

# Security settings - made less restrictive for debugging
# Most security features disabled to avoid potential issues during development/debugging
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = None  # Disabled
# SECURE_HSTS_SECONDS = 31536000  # Disabled
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Disabled
# SECURE_HSTS_PRELOAD = True  # Disabled

# Content Security - relaxed
SECURE_CONTENT_TYPE_NOSNIFF = False  # Disabled
SECURE_BROWSER_XSS_FILTER = False  # Disabled
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allow iframes

# CSRF Protection - relaxed
CSRF_COOKIE_SECURE = False  # Disabled for easier debugging
CSRF_COOKIE_HTTPONLY = False  # Disabled for easier debugging
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions

# ERROR HANDLERS
handler404 = 'attendance.views.handler404'
handler403 = 'attendance.views.handler403'
handler500 = 'attendance.views.handler500'
handler400 = 'attendance.views.handler400'

# django session Timeout


LOGIN_URL = '/'  
LOGOUT_REDIRECT_URL = '/' 
AUTO_LOGOUT = {
    'IDLE_TIME': 10000,
    'SESSION_TIME': 16000,
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
    'REDIRECT_URL': '/'  # The URL to redirect to after logout
}
